### PR TITLE
Create New Things

### LINKED ISSUE #18: Create a new thing!
Need a way to create a new thing.

Need:
- new route
- component
- tests!
- Location view should have button to create a new thing (maybe a plus near the location name)

### PR DESCRIPTION
**Pull request by alecho**
Will close #18

### CODE REVIEW

**Comment by ryoe** [comment]
The more I've thought about this I started to wonder if it might be a good idea to:
- add route `/locations/:location_id/newthing` for creating new things directly tied to a known location
    - in this case`thing-form` wouldn't allow changing locations
- add route `/things/` to show All The Things!
    - we could also fitlers by location, types, etc.
- add route `/things/new` for creating new things from the list of things
    - in this case `thing-form` would allow choosing location from list of known locations

I actually started adding `/things/` in my branch, if you like I could break it out and do a separate PR that's completely independent of what's happening in this branch.

**Comment by alecho** [comment]
@ryoe I like this.

I've been thinking that we need to change `/locations/:id/` to `/locations/:id/things` (either the index or the list route). This allows for a `new` route nested under `/locations/:id/things`.

A `/things` route makes sense but I'm not sure how much sense it makes right now as in production we'll only have one location.

`things/new` seems like a good idea but it implies `/things` exists.

Your welcome to do a separate PR for `/things`. I'm afraid trying to squeeze them I'm here will get confusing.

**Comment by alecho** [comment]
Looks good to merge to me. @ryoe?

**Comment by alecho** [comment]
Actually I just say you have a separate PR for the `things/list` route stuff. Let me know if you want me to extract it from this branch @ryoe.

**Comment by ryoe** [comment]
@alecho I think this PR and #25 are complementary.

This PR is handling creating new things and listing things associated with specific locations. #25 is an attempt to list things in general, independent of any given location. But maybe, I'm thinking about it wrong. 

So yes, I say merge this PR and we can talk more about #25 if you like.

**Pull request merged**
